# NOTE: This name appears in GitHub's Checks API and in workflow's status badge.
name: ci-test

# Trigger the workflow when:
on:
  # A push occurs to one of the matched branches.
  push:
    branches:
      - master
      - stable/*
  # Or when a pull request event occurs for a pull request against one of the
  # matched branches.
  pull_request:
    branches:
      - master
      - stable/*

jobs:

  e2e-ts-web:
    # NOTE: This name appears in GitHub's Checks API.
    name: e2e-ts-web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js LTS
        uses: actions/setup-node@v2.1.4
        with:
          node-version: "12.x"

      - name: Set up npm
        run: npm install npm@7 -g

      # TODO: Get rid of this after we publish oasis-sdk packages.
      - name: Set up oasis-sdk packages
        working-directory: /tmp
        run: |
          set -x
          git clone https://github.com/oasisprotocol/oasis-sdk.git
          cd oasis-sdk/client-sdk/ts-web
          git switch pro-wh/feature/master
          npm install
          (cd core && npm run-script prepare)
          (cd rt && npm run-script prepare)
          ls -al core # %%%
          ls -al core/dist # %%%
          cd "$GITHUB_WORKSPACE/client-sdk/ts-web"
          npm link /tmp/oasis-sdk/client-sdk/ts-web/core /tmp/oasis-sdk/client-sdk/ts-web/rt
          ls -al node_modules/@oasisprotocol # %%%
          stat node_modules/@oasisprotocol/client/package.json # %%%

      - name: Install Node deps
        working-directory: client-sdk/ts-web
        run: |
          npm ci || true
          locale # %%%
          find . -type f -exec md5sum {} \; | sort -k2 > sum.md5 # %%%

      - name: Upload # %%%
        uses: actions/upload-artifact@v2
        with:
          name: sum.md5
          path: client-sdk/ts-web/sum.md5
